services:
  chat_server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  chat_client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - chat_server

  redis:
    image: redis:alpine